---

# This role installs apt packages listed in the "apt_packages" variable tree.
#
# Wrapper for: http://docs.ansible.com/ansible/latest/modules/apt_module.html
#

- name: Install apt packages
  apt:
    name: "{{ item }}"
    update_cache: false
    state: present
  with_items: "{{ apt_packages }}"
